### ISSUE TITLE
One too much popped in TSudokuStack.RevertToMark ?

### ISSUE THREAD

**Issue by federgraph** [PeterBelow/SudokuHelper#1]
https://github.com/PeterBelow/SudokuHelper/blob/ca165590bfa8edf83bc84f29c46ae8d127c75d9d/BaseSudokuDataStorageU.pas#L968

Fix should be easy:

`      while Count > LMark.Count + 1 do // + 1 added
        Pop;
`

**Comment by PeterBelow** [comment]
That's actually working as intended. When I come to a branch in the Sudoku I set one of the possible values in the cell, then set the mark. When that turns out to be a dead end I revert to the mark and want to be at the point **before** setting the value that turned out to be the wrong choice.
